- hosts: test
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  tasks:
 
  - name: Add Docker s official GPG key
    remote_user: edureka
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    remote_user: edureka
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    remote_user: edureka
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: edureka
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker
    remote_user: edureka
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
  - name: Add remote "edureka" user to "docker" group
    remote_user: edureka
    user:
      name: "edureka"
      group: "docker"
      append: yes
    tags:
      - docker
  - name: Start the container
    remote_user: edureka
    docker_container:
      name: appSample
      image: "roynitishdev/webapp"
      state: started
      published_ports:
        - 0.0.0.0:8080:8080  
    
    